---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicroservice1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mymicroservice1
    spec:
      containers:
      - name: mymicroservice1-container
        image: dheerajbhavsar89/mymicroservice1:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: mymicroservice1
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice1
